site_name: The Cask Book
theme:
  name: material

  features:
    - content.code.copy
    - toc.integrate

  language: en

  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Introduction: index.md
  - 1. Getting Started: getting-started.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

copyright: |
  &copy; 2024 <a href="https://github.com/cpp-cask"  target="_blank" rel="noopener">Cask Authors</a>