#include <fmt/color.h>
#include <fmt/core.h>

#include <cask/ops/cask_help.hpp>
#include <cask/ops/cask_new.hpp>
#include <cask/util/filesystem.hpp>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <string_view>

namespace fs = std::filesystem;

namespace cask {
namespace new_ {

namespace {
[[nodiscard]] OpResult error_missing_path() {
  return help::fatal_error(fmt::format(
      R"(the following required arguments were not provided:
{}

{} {} {}

For more information, try '{}'
)",
      fmt::format(fg(help::blue) | fmt::emphasis::bold, "  <path>"),
      fmt::format(fg(help::green) | fmt::emphasis::bold, "Usage:"),
      fmt::format(fg(help::blue) | fmt::emphasis::bold, "cask new"),
      fmt::format(fg(help::blue), "<path>"),
      fmt::format(fg(help::blue) | fmt::emphasis::bold, "--help")));
}

[[nodiscard]] OpResult error_directory_exists(
    const std::string_view project_name) {
  return help::fatal_error(fmt::format(
      R"(destination `{}` already exists

Use `cask init` to initialize the directory
)",
      fs::absolute(project_name).string()));
}
}  // namespace

OpResult exec(const std::span<char *> args) {
  if (args.empty()) {
    return error_missing_path();
  }

  const auto project_name = args[0];

  if (fs::is_directory(project_name)) {
    return error_directory_exists(project_name);
  }

  fs::path path{project_name};

  fs::create_directories(path);
  fs::create_directories(path / "src");

  auto file = filesystem::ofstream(path / "src" / "main.cpp");

  if (!file) {
    return file.error();
  }

  *file << R"(#include <iostream>

int main() {
    std::cout << "Hello World!\n";
}
)";

  file->close();

  file = filesystem::ofstream(path / ".gitignore");

  if (!file) {
    return file.error();
  }

  *file << R"(# Generated by Cask
# will have compiled files and executables
debug/
target/)";

  file->close();

  file = filesystem::ofstream(path / "Cask.toml");

  if (!file) {
    return file.error();
  }

  *file << fmt::format(R"([package]
name = "{}"
version = "0.1.0"
standard = "20"

[dependencies]
)",
                       project_name);

  file->close();

  return fmt::format(
      R"(     {} binary (application) `{}` package
{} see more `Cask.toml` keys and their definitions at https://doc.cplusplus-lang.com/cask/reference/manifest.html
)",
      fmt::format(fg(fmt::color::light_green) | fmt::emphasis::bold, "Created"),
      project_name,
      fmt::format(fg(fmt::color::deep_sky_blue) | fmt::emphasis::bold,
                  "note:"));
}

}  // namespace new_
}  // namespace cask
