[book]
title = "The Cask Book"
author = "Ismael Jimenez, Alex Crichton, Steve Klabnik and Carol Nichols, with contributions from the Cask and Rust community"

[output.html]
smart-punctuation = true # Enable smart-punctuation feature for more than quotes.
git-repository-url = "https://github.com/cplusplus-lang/cask/tree/main/src/doc/src"
edit-url-template = "https://github.com/cplusplus-lang/cask/edit/main/src/doc/{path}"
search.use-boolean-and = true

[output.html.redirect]
"/guide/build-cache.html" = "../reference/build-cache.html"
