name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up CMake
      - name: Install CMake
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install cmake -y

      - name: Install CMake (Windows)
        if: matrix.os == 'windows-latest'
        uses: chrislgarry/setup-cmake@v1

      - name: Install CMake (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install cmake

      # Configure the project
      - name: Configure with CMake
        run: cmake -S . -B build

      # Build the project
      - name: Build with CMake
        run: cmake --build build

      # Run the executable (optional)
      - name: Run executable (Linux/Mac)
        if: matrix.os != 'windows-latest'
        run: ./build/cask

      - name: Run executable (Windows)
        if: matrix.os == 'windows-latest'
        run: .\build\Debug\cask.exe
