name: CI

on: [push, pull_request]

environment:
  name: github-pages

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup update nightly && rustup default nightly
    - run: rustup update stable
    - run: rustup component add rust-docs
    # This requires rustfmt, use stable.
    # - name: Run semver-check
    #   run: cargo +stable run -p semver-check
    # - name: Ensure intradoc links are valid
    #   run: cargo doc --workspace --document-private-items --no-deps
    #   env:
    #     RUSTDOCFLAGS: -D warnings
    - name: Install mdbook
      run: |
        mkdir mdbook
        curl -Lf https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH
    - run: cd src/doc && mdbook build --dest-dir ../../target/doc
    # - name: Run linkchecker.sh
    #   run: |
    #     cd target
    #     curl -sSLO https://raw.githubusercontent.com/rust-lang/rust/master/src/tools/linkchecker/linkcheck.sh
    #     sh linkcheck.sh --all --path ../src/doc cargo

    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: target/doc
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

